### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by Nic30** [Nic30/pycocotb#5]
Current state of the Verilator makes it very hard to compile it on windows as a library and link it with python.

This is at least 120h job with significant impact on Verilator. 
* Namely autotools has to be replaced by meson, cmake or by something  which works everywhere. The Verilator also contains many scripts in Perl, which are tied to autotools and most importantly they are entirely useless as the Cmake/Meson-build can run tests/generate configs etc.

I do have "verilator with the meson"  (https://github.com/Nic30/verilator-meson, not everything is pushed.)
It is perfectly working however there is still a lot of useless Perl.
I was talking with the the Wilson Snyder (author of the Verilator) and he was not convinced that Meson is required.

So the question is if we want to push Verilator to meson (or something else) so we can have multiplatform support with a proper installation. Or if we do not need a Windows support etc.

**Comment by ycrad** [comment]
The first idea to pop into my head is that this is an ideal problem for Docker to solve.

Since 2013, Docker can run on many Linux, Unix, and MAC hosts.
And since 2015 Docker can run on Windows 10 and Windows 10 Server.

So just support Windows 10 via a Docker Container (eg: with Ubuntu 14.04 inside).

Then you can have the proper versions of Perl and Autotools installed and can link the libraries with the correct Python version
- Without worrying about Windows problems

**Comment by Nic30** [comment]
I silently hope so.
